### ISSUE TITLE
Feature request: dry-contact inputs, esphome

### ISSUE THREAD

**Issue by ptr727** [Chrismettal/ESP-Hiro#2]
I've long been looking for a general purpose ESP32 board with a variety of IO, very cool project.
For future versions I'd like to see ESP32, ESPHome templates (natieve HomeAssitant support), LiPo charging backup power, 2+ inputs for dry-contact switches used for pule counting (connecting to utility meters), off-board antenna plug (could be part of ESP32 package, but accounted for in case STL file).

**Comment by Chrismettal** [comment]
Thank you!

At this time I do not yet see the advantage of ESP32s in this application. What are the usecases for you where a ESP8266 doesn't suffice? An ESP32 version isn't impossible though.

Likewise I have not touched ESPHome at all and instead focused on Tasmota. Gotta take a look at ESPHome and then maybe push a template.

For dry contact switches you can use any GPIO you want and even the PCF ports. I do not know if the PCFs pulse counting is supported in Tasmota at this time, but I am pulse counting over GPIOs. The only thing missing are headers that specifically have GND and GPIO side by side, as I didn't want to waste expensive header contacts on multiple GND points, especially because I often route 3-4 switches with just one GND which could fit to one header then.

Battery backup and an external antenna are actually both part of my next project, which will be a weather station PCB based on the ESP-Hiro design, including Batteries, Solar power, and potentially a bigger antenna to make it into your home Wifi!

Thanks for your feedback!
